### ISSUE TITLE
TlistviewEx not found

### ISSUE THREAD

**Issue by johnjohnsp1** [diversenok/TokenUniverse#1]
Hello , thanks for sharing the code , is a pretty nice one,
i'm telling you about the error i get during compile from source stage :
Loading the project with:

-Virtual Machine Windows 10 21h1 Build 19043, 1151
-Delphi 10.4 and C++ Builder 10.4 update 2
getting the error about <TlistViewEx> (see attach) , i then click ignore in order to proceed and once loaded the project
![tlistviewEx](https://user-images.githubusercontent.com/1888855/140923339-70de291e-887b-43f4-87d1-6fdfac8463b1.PNG)
getting few errors within the build/compile stage:
-Field FormMain.ListView Tokens does not have a corresponding component.  Remove the declaration ?

![Listviewmain](https://user-images.githubusercontent.com/1888855/140923775-740c4f11-3b4c-445e-a150-60f2ccde13fa.PNG)

then i continue clicking "yes" and the final output is telling me more errors:
![build](https://user-images.githubusercontent.com/1888855/140923993-8ae2827e-e6ca-4986-a3ea-73c53505edb5.PNG)

-Class TVirtualStringTree not found .. continue with the all others error all around
..
![uiprototype](https://user-images.githubusercontent.com/1888855/140924231-84ff052d-4e85-43b6-96d5-7dfe30f1cc1f.PNG)

im doing something wrong ?
let me know if you can please, 

thanks

**Comment by diversenok** [comment]
Hello. Thanks for the interest in the project!

There are a few steps you need to take before building the tool in the IDE for the first time:

1. Install **VirtualTree** via Tools -> GetIt Package Manager
![GetIt](https://user-images.githubusercontent.com/30962924/140928757-6344c647-9e83-4679-8dbe-dc078f68fa53.png)

2.  Open **NtUtilsUI\\VclEx\\VclExtension.dproj** and click *Install*
![VclEx](https://user-images.githubusercontent.com/30962924/140929873-a8ef5371-6789-4509-8221-faf9a5c65af4.png)

These steps will register the required visual components with the IDE, so it knows how to use them in the designer and while building the project. Let me know if you have any other problems afterward since I might've forgotten something.

I will update the readme with the build steps shortly 👍

**Comment by johnjohnsp1** [comment]
awesome, thanks for the reply, after doing all your steps is building without any problems.
thanks once more really interesting project !!
